### ISSUE TITLE
Call logs dont refresh

### ISSUE THREAD

**Issue by nihal697** [AICP/kernel_xiaomi_sdm660#1]
Hi, call logs dont refresh until and unless the dialer is closed and opened agsin. Please consider fixing it. Its been a while now :(

**Comment by eyosen** [comment]
We are considering it but unfortunately they don't get fixed themselves. Also, interesting for you to post this here in a kernel repo....

**Comment by nihal697** [comment]
Ah, extremely sorry I was high and didnt conprehend that its a kernel repo. I understand that the issues dont get fixed themselves, but I provided logs too to lavender developer in the Telegram group for it. Anything else on my part that I could do,  please let me know. :D
